import 'legal_links.dart';
import 'secure_strings.dart';

// ============================================================
// APP FACADE — single access point for app-wide constants
// ============================================================
// Identity values are plain; endpoints/credentials resolve lazily
// through the obfuscator so plaintext never lands in the binary.
//
// ⚠️ TEMPLATE — every field marked with [TODO] must be filled per
// project before the first build. Leaving `[TODO]` values in place
// is safe (the app degrades to the offline / native game path) but
// gray mode will never activate until real credentials land.
// ============================================================

class TowerFacade {
  TowerFacade._();

  // ─────────────────────────────────────────────────────────
  // Identity
  // ─────────────────────────────────────────────────────────
  //
  // [TODO] Replace all three with values received from the manager.
  //
  // packageId  — Android applicationId + iOS bundle id.
  //              Must EXACTLY match:
  //                • android/app/build.gradle.kts → applicationId
  //                • android/app/build.gradle.kts → namespace
  //                • ios/Runner.xcodeproj CFBundleIdentifier
  //                • android/app/google-services.json → package_name
  //
  // marketId   — Store id. On Android this is identical to packageId.
  //              On iOS you MUST prefix the numeric App Store id with
  //              literal `id`, e.g. `id84435554334`. This is the value
  //              sent to the config endpoint as `store_id`.
  //
  // displayName — Human-readable app name exactly as it will appear
  //               in the store listing. Must match `android:label` in
  //               AndroidManifest.xml.
  //
  // [FINGERPRINT] Never reuse a real packageId across projects. Even
  // the app-suffix should differ (e.g. skywardtowers → cloudpickers
  // → mossglade). Package name diversity is one of the primary
  // fingerprint signals for store scanners.
  static const String packageId = 'com.example.template'; // [TODO]
  static const String marketId = 'com.example.template'; // [TODO]
  static const String displayName = 'Template App'; // [TODO]

  // iOS App Store numeric id (unused on Android — keep empty).
  static const String storeNumericId = ''; // [TODO iOS builds only]

  // ─────────────────────────────────────────────────────────
  // Resolved endpoints / credentials
  // ─────────────────────────────────────────────────────────
  // These come from `secure_strings.dart`, which is generated by
  // `dart run tool/secret_packer.dart`. On a fresh template the
  // byte arrays are empty → these getters return "" → the config
  // path fails gracefully and the app opens the native game.
  static String get gateEndpoint => unlockConfigEndpoint();
  static String get attributionKey => unlockAttributionKey();
  static String get messagingProject => unlockMessagingProject();

  // ─────────────────────────────────────────────────────────
  // Public links (kept as plain strings — non-sensitive)
  // ─────────────────────────────────────────────────────────
  static const String privacyUrl = privacyPolicyLink;
  static const String helpUrl = supportLink;
  static const String homeUrl = siteHome;

  // ─────────────────────────────────────────────────────────
  // Timing knobs
  // ─────────────────────────────────────────────────────────
  // Re-prompt the push invite this many seconds after a Skip (3 days).
  // Per TZ §"Push permission" — do NOT lower this without approval.
  static const int pushInviteCooldown = 3 * 24 * 60 * 60;

  // Delay before retrying attribution via GCD when the first
  // callback reports a (possibly false) Organic status.
  // See android_gray_guide.md §"AppsFlyer Organic False-Positive Fix".
  static const int organicRecheckDelay = 5;
}
